#!/usr/bin/env bash

# Turn off echo 关闭回显
set +x

# 将工作目录设置为脚本所在目录
# shellcheck disable=SC2164
cd "$(dirname "$0")"

git remote -v
git status

coreFolder="Flutter3Core"
if [ -d "$PWD/$coreFolder" ]; then
    # shellcheck disable=SC2164
    cd $coreFolder
    git remote -v
    git status
    # shellcheck disable=SC2103
    cd ..
fi

extendFolder="Flutter3Extend"
if [ -d "$PWD/$extendFolder" ]; then
    # shellcheck disable=SC2164
    cd $extendFolder
    git remote -v
    git status
    # shellcheck disable=SC2103
    cd ..
fi

desktopFolder="Flutter3Desktop"
if [ -d "$PWD/$desktopFolder" ]; then
    # shellcheck disable=SC2164
    cd $desktopFolder
    git remote -v
    git status
    # shellcheck disable=SC2103
    cd ..
fi

abcFolder="Flutter3Abc"
# shellcheck disable=SC2164
if [ -d "$PWD/$abcFolder" ]; then
    cd $abcFolder
    git remote -v
    git status
    # shellcheck disable=SC2103
    cd ..
fi

# read -n 1 -s -r -p "!结束! Press any key to continue..."
